### ISSUE TITLE
Add note about this being supported natively in Firefox

### ISSUE THREAD

**Issue by simevidas** [olahol/express-chrome-logger#2]
The Firefox DevTools console now has native support for server-sent console messages. I’ve tested in Firefox Nightly: [see screenshot](https://twitter.com/simevidas/status/659502899786027008).

I’m not sure when this will reach Firefox stable, but still, I think it’s worth noting in your README that this support exists in Firefox natively.

**Comment by olahol** [comment]
Interesting, I will absolutely add it.

**Comment by olahol** [comment]
A notice about Firefox Nightly has been added in version `0.1.4`, thank you :+1:.
